---
- name: Converge
  hosts: all

  roles:
    - role: boutetnico.cron
      cron_jobs:
        - name: "run backup script every 6 hours as admin"
          job: backup.sh
          hour: "*/6"
          minute: 0
          user: admin
        - name: "delete files in /tmp every hour as root"
          job: "rm -rf /tmp"
          special_time: "hourly"
        - name: "rsync files between 2 directories every 15 minutes using /etc/cron.d/rsync as root"
          job: "rsync -a /mnt /backup"
          cron_file: "rsync"
          user: root
        - name: "backup database daily using /etc/cron.d/backup_database as admin"
          job: "/home/admin/mysqldump.sh"
          cron_file: "backup_database"
          special_time: "daily"
          user: admin
