---
dependency:
  name: galaxy
  enbaled: False

driver:
  name: docker

platforms:
  - name: ansible-role-cron-debian-9
    image: debian:9
  - name: ansible-role-cron-debian-10
    image: debian:10
  - name: ansible-role-cron-ubuntu-1804
    image: ubuntu:18.04
  - name: ansible-role-cron-ubuntu-2004
    image: ubuntu:20.04

lint: |
    yamllint .
    ansible-lint
    flake8

provisioner:
  name: ansible

verifier:
  name: testinfra
